[pytest]
addopts = --tb=line
norecursedirs = .git config output src .pytest_cache
testpaths = tests/unit tests/integration
pythonpath = src/jobs
markers =
    unit: Quick unit tests (no external dependencies)
    integration: Slower integration tests (requires Databricks Connect)